CREATE TABLE IF NOT EXISTS `USER` (
    `id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
    `name` VARCHAR(255) NOT NULL,
    `phoneNumber` VARCHAR(11) NOT NULL UNIQUE,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `DRIVER` (
    `id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE ,
    `payment` VARCHAR(10) NOT NULL,
    `license` VARCHAR(22) NOT NULL UNIQUE ,
    `userId` BIGINT NOT NULL UNIQUE ,
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES USER(id)
);